"""Central runtime versions recorded in Case state, audits and generated outputs."""

APP_VERSION = "0.1.0"
CASE_OBJECTIVE_VERSION = "case-objective-1.0"
QUESTIONNAIRE_VERSION = "demo-questionnaire-1.0"
RULESET_VERSION = "demo-rules-1.0"
WORKFLOW_VERSION = "airo-case-coordinator-0.2"
PROMPT_VERSION = "demo-prompts-0.2"
AGENT_POLICY_VERSION = "illustrative-demo-agent-policy-1.0"
AUTONOMY_POLICY_VERSION = "demo-autonomy-1.0"
GATE_VERSION = "airo-gates-1.0"
TOOL_CONTRACT_VERSION = "demo-1.0"
MATERIALITY_RULE_VERSION = "demo-materiality-1.0"
LOD2_TRIGGER_VERSION = "demo-2lod-1.0"
