"""Central runtime versions recorded in Case state, audits and generated outputs."""

APP_VERSION = "0.2.0"
UI_ASSET_VERSION = "ui-2026-08-25-9"
CASE_OBJECTIVE_VERSION = "case-objective-1.0"
QUESTIONNAIRE_VERSION = "demo-questionnaire-1.0"
RULESET_VERSION = "demo-rules-1.0"
WORKFLOW_VERSION = "airo-case-coordinator-0.3"
PROMPT_VERSION = "demo-prompts-0.2"
AGENT_POLICY_VERSION = "illustrative-demo-agent-policy-2.0"
AUTONOMY_POLICY_VERSION = "demo-autonomy-1.0"
GATE_VERSION = "airo-governance-loops-2.1"
TOOL_CONTRACT_VERSION = "demo-tool-contract-2.0"
CASE_STATE_SCHEMA_VERSION = "airo-case-state-2.0"
EXTERNAL_EVENT_SCHEMA_VERSION = "demo-external-event-1.0"
MATERIALITY_RULE_VERSION = "demo-materiality-1.0"
LOD2_TRIGGER_VERSION = "demo-2lod-1.0"
